/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.layout;

/**
 *
 * @author farras
 */
public class CardLayoutPesan extends javax.swing.JFrame {

    /**
     * Creates new form CardLayoutPesan
     */
    public CardLayoutPesan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPilih = new javax.swing.JPanel();
        lblLangkah1 = new javax.swing.JLabel();
        lblNamaKopi = new javax.swing.JLabel();
        txtKopi = new java.awt.TextField();
        btnLanjut = new javax.swing.JButton();
        panelkonfirmasi = new javax.swing.JPanel();
        lblLangkah2 = new javax.swing.JLabel();
        lblPesanan = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblLangkah1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLangkah1.setText("Langkah 1 dari 2 - Pilih Kopi");

        lblNamaKopi.setText("Nama Kopi:");

        txtKopi.setText("Latte");
        txtKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKopiActionPerformed(evt);
            }
        });

        btnLanjut.setText("Lanjut");
        btnLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanjutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPilihLayout = new javax.swing.GroupLayout(panelPilih);
        panelPilih.setLayout(panelPilihLayout);
        panelPilihLayout.setHorizontalGroup(
            panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilihLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLangkah1)
                    .addGroup(panelPilihLayout.createSequentialGroup()
                        .addComponent(lblNamaKopi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPilihLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLanjut)
                .addContainerGap())
        );
        panelPilihLayout.setVerticalGroup(
            panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilihLayout.createSequentialGroup()
                .addComponent(lblLangkah1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamaKopi)
                    .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(btnLanjut)
                .addGap(15, 15, 15))
        );

        getContentPane().add(panelPilih, "pilih");

        lblLangkah2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblLangkah2.setText("Langkah 2 dari 2 - Konfirmasi");

        lblPesanan.setText("Kopi yang dipilih: -");

        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelkonfirmasiLayout = new javax.swing.GroupLayout(panelkonfirmasi);
        panelkonfirmasi.setLayout(panelkonfirmasiLayout);
        panelkonfirmasiLayout.setHorizontalGroup(
            panelkonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelkonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLangkah2)
                    .addComponent(lblPesanan))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelkonfirmasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(27, 27, 27)
                .addComponent(btnSelesai)
                .addContainerGap())
        );
        panelkonfirmasiLayout.setVerticalGroup(
            panelkonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkonfirmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLangkah2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addGroup(panelkonfirmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        getContentPane().add(panelkonfirmasi, "konfirmasi");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKopiActionPerformed

    private void btnLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanjutActionPerformed
        // TODO add your handling code here:
        lblPesanan.setText("Kopi yang dipilih: " + txtKopi.getText());
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "konfirmasi");
    }//GEN-LAST:event_btnLanjutActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "pilih");
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Pesanan disimpan.");
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardLayoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardLayoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardLayoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardLayoutPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardLayoutPesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLanjut;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel lblLangkah1;
    private javax.swing.JLabel lblLangkah2;
    private javax.swing.JLabel lblNamaKopi;
    private javax.swing.JLabel lblPesanan;
    private javax.swing.JPanel panelPilih;
    private javax.swing.JPanel panelkonfirmasi;
    private java.awt.TextField txtKopi;
    // End of variables declaration//GEN-END:variables
}
